<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>Castle.Facilities.NHibernateIntegration</AssemblyName>
    <RootNamespace>Castle.Facilities.NHibernateIntegration</RootNamespace>

    <Title>Castle.Facilities.NHibernateIntegration</Title>
    <Description>Castle.Facilities.NHibernateIntegration</Description>

    <PackageId>Castle.Facilities.NHibernateIntegration</PackageId>
    <PackageDescription>Castle.Facilities.NHibernateIntegration</PackageDescription>
    <PackageTags>Castle; Facility; NHibernate; NHibernateIntegration</PackageTags>
    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net48'))">
    <PackageReference Include="Nullable" PrivateAssets="All" />
  </ItemGroup>

</Project>
